name: iosApp
options:
  bundleIdPrefix: com.bryanollivie
  deploymentTarget:
    iOS: "16.0"
settings:
  DEVELOPMENT_TEAM: ""
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.bryanollivie.resume
      INFOPLIST_FILE: iosApp/Info.plist
      FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]:
        - "$(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework"
      FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]:
        - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
      OTHER_LDFLAGS:
        - "-framework"
        - "ComposeApp"
    dependencies: []
